import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { Resvg } from '@resvg/resvg-js'

import { BRAND, MARK_INSET_VIEW_BOX, MARK_PATH, MARK_VIEW_BOX } from '../src/data/brand.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const publicDir = join(root, 'public')

const brandDir = join(publicDir, 'brand')

const cacheDir = join(root, '.cache', 'brand')

const BANNER = [
  'Generated by scripts/build-icons.mjs from src/data/brand.ts.',
  'Do not edit this file: run `npm run icons` after changing that module.',
].join(' ')

const MASKABLE_SCALE = 0.55

const scaledAboutCentre = (scale) => `translate(32 32) scale(${scale}) translate(-32 -32)`

const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${MARK_INSET_VIEW_BOX}">
  <!-- ${BANNER} -->
  <style>
    .mark { fill: ${BRAND.background} }
    @media (prefers-color-scheme: dark) { .mark { fill: ${BRAND.onDark} } }
  </style>
  <path class="mark" d="${MARK_PATH}"/>
</svg>
`

const maskable = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${MARK_VIEW_BOX}">
  <!-- ${BANNER} -->
  <rect width="64" height="64" fill="${BRAND.background}"/>
  <g transform="${scaledAboutCentre(MASKABLE_SCALE)}">
    <path d="${MARK_PATH}" fill="${BRAND.onDark}"/>
  </g>
</svg>
`

const OG_WIDTH = 1200
const OG_HEIGHT = 630
const OG_STEP = 40

function gridLines() {
  const lines = []
  for (let x = OG_STEP; x < OG_WIDTH; x += OG_STEP) {
    lines.push(`<path d="M${x} 0V${OG_HEIGHT}"/>`)
  }
  for (let y = OG_STEP; y < OG_HEIGHT; y += OG_STEP) {
    lines.push(`<path d="M0 ${y}H${OG_WIDTH}"/>`)
  }
  return `<g stroke="${BRAND.grid}" stroke-width="1" fill="none">${lines.join('')}</g>`
}

const openGraph = `<svg xmlns="http://www.w3.org/2000/svg" width="${OG_WIDTH}" height="${OG_HEIGHT}" viewBox="0 0 ${OG_WIDTH} ${OG_HEIGHT}">
  <!-- ${BANNER} -->
  <rect width="${OG_WIDTH}" height="${OG_HEIGHT}" fill="${BRAND.background}"/>
  ${gridLines()}
  <rect x="48" y="48" width="${OG_WIDTH - 96}" height="${OG_HEIGHT - 96}" fill="none" stroke="${BRAND.border}" stroke-width="2"/>
  <path d="M48 128V48h80" fill="none" stroke="${BRAND.accent}" stroke-width="4"/>
  <path d="M${OG_WIDTH - 48} ${OG_HEIGHT - 128}v80h-80" fill="none" stroke="${BRAND.accent}" stroke-width="4"/>
  <g transform="translate(${OG_WIDTH / 2} ${OG_HEIGHT / 2}) scale(2) translate(-32 -32)">
    <path d="${MARK_PATH}" fill="${BRAND.onDark}"/>
  </g>
</svg>
`

async function renderPng(svg, width) {
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: width },

    shapeRendering: 2,
    logLevel: 'error',
  })
  return resvg.render().asPng()
}

const rasterOutputs = [
  ['apple-touch-icon.png', maskable, 180],
  ['icon-maskable.png', maskable, 512],
  ['og.png', openGraph, OG_WIDTH],
]

const outputs = [
  ['favicon.svg', favicon],
  ['icon-maskable.svg', maskable],
]

mkdirSync(brandDir, { recursive: true })

for (const [name, contents] of outputs) {
  writeFileSync(join(brandDir, name), contents, 'utf8')
  console.log(`[icons] public/brand/${name}  ${contents.length} bytes`)
}

for (const [name, svg, width] of rasterOutputs) {
  const png = await renderPng(svg, width)
  writeFileSync(join(brandDir, name), png)
  console.log(`[icons] public/brand/${name}  ${png.length} bytes  ${width}px wide`)
}

mkdirSync(cacheDir, { recursive: true })
writeFileSync(join(cacheDir, 'og.svg'), openGraph, 'utf8')
console.log(`[icons] .cache/brand/og.svg  ${openGraph.length} bytes  (not served)`)

const og = readFileSync(join(brandDir, 'og.png'))
const ogWidth = og.readUInt32BE(16)
const ogHeight = og.readUInt32BE(20)
const seo = readFileSync(join(root, 'src/lib/seo.ts'), 'utf8')
const declared = /OG_IMAGE = \{ width: (\d+), height: (\d+) \}/.exec(seo)
if (!declared) {
  throw new Error('[icons] could not find OG_IMAGE in src/lib/seo.ts')
}
if (Number(declared[1]) !== ogWidth || Number(declared[2]) !== ogHeight) {
  throw new Error(
    `[icons] og.png is ${ogWidth}x${ogHeight} but src/lib/seo.ts declares ` +
      `${declared[1]}x${declared[2]}. Update OG_IMAGE there.`,
  )
}
console.log(`[icons] og.png size matches the og:image tags (${ogWidth}x${ogHeight})`)
